version: "3.8"

services:
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"            # host port 80 exposed by nginx proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
      - pma
    networks:
      - frontend

  wordpress:
    image: wordpress:php8.1-apache
    container_name: wordpress
    restart: always
    env_file: 
      - .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend
    # Do NOT publish wordpress port to host; nginx will proxy to it.

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - frontend

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - frontend
    # no host port; nginx proxies to this service

volumes:
  wp_data:
  db_data:

networks:
  frontend:
    driver: bridge

